let arr=[10,25,40,15,30], base=1000, size=4;
let linear={i:0,target:null,count:0,run:false}, binary={low:0,high:-1,target:null,count:0,run:false};

function setArray(){const raw=document.getElementById("arrayInput").value;const vals=raw.split(/[, ]+/).map(Number).filter(Number.isFinite);if(vals.length){arr=vals.slice(0,14);renderArray();log("modifyLog","Array rebuilt with "+arr.length+" penguins.");}}
function randomArray(){arr=Array.from({length:7},()=>Math.floor(Math.random()*90)+10);document.getElementById("arrayInput").value=arr.join(", ");renderArray();log("modifyLog","A fresh penguin colony has arrived!");}
function renderArray(active=-1){const box=document.getElementById("arrayVisual");box.innerHTML="";arr.forEach((v,i)=>{const c=document.createElement("div");c.className="cell";c.innerHTML=`<div class="addr">📍 ${base+i*size}</div><span class="penguin ${i===active?"active":""}">🐧</span><div class="value">${v}</div><div class="index">INDEX ${i}</div>`;box.appendChild(c)})}
function log(id,msg){document.getElementById(id).textContent=msg}
function calcAddress(){base=Number(document.getElementById("base").value)||0;size=Number(document.getElementById("size").value)||1;const i=Number(document.getElementById("addrIndex").value)||0;renderArray();const a=base+i*size;document.getElementById("addressResult").innerHTML=`LOC(A[${i}]) = ${base} + (${i} × ${size}) = <strong>${a}</strong> bytes`;renderArray(i)}
function insertAt(){let v=Number(document.getElementById("modValue").value),p=Number(document.getElementById("modPos").value);if(!Number.isFinite(v)||p<0||p>arr.length){log("modifyLog","Choose a valid value and position.");return}arr.splice(p,0,v);document.getElementById("arrayInput").value=arr.join(", ");renderArray(p);log("modifyLog",`Inserted 🐧${v} at index ${p}. Elements to the right shifted one position.`)}
function deleteAt(){let p=Number(document.getElementById("modPos").value);if(p<0||p>=arr.length){log("modifyLog","Choose a valid existing index.");return}let v=arr.splice(p,1)[0];document.getElementById("arrayInput").value=arr.join(", ");renderArray(Math.min(p,arr.length-1));log("modifyLog",`Deleted 🐧${v} from index ${p}. Remaining elements shifted left.`)}
function startLinear(){linear={i:0,target:Number(document.getElementById("linearTarget").value),count:0,run:true};renderArray();document.getElementById("linearCount").textContent=0;document.getElementById("linearStatus").textContent="Searching…";log("linearLog","Starting at index 0.");}
function linearStep(){if(!linear.run){return}if(linear.i>=arr.length){linear.run=false;document.getElementById("linearStatus").textContent="Not Found";log("linearLog",`Checked all ${linear.count} positions. Target ${linear.target} is not in the array.`);return}renderArray(linear.i);linear.count++;document.getElementById("linearCount").textContent=linear.count;let v=arr[linear.i];if(v===linear.target){linear.run=false;document.getElementById("linearStatus").textContent="Found ✓";log("linearLog",`🐧${v} matches target at index ${linear.i}.`);return}log("linearLog",`Index ${linear.i}: ${v} ≠ ${linear.target}. Move to the next penguin.`);linear.i++}
function startBinary(){arr.sort((a,b)=>a-b);document.getElementById("arrayInput").value=arr.join(", ");binary={low:0,high:arr.length-1,target:Number(document.getElementById("binaryTarget").value),count:0,run:true};updateRange();renderArray();document.getElementById("binaryCount").textContent=0;document.getElementById("binaryStatus").textContent="Searching…";log("binaryLog","Array sorted. Start with the full search range.");}
function updateRange(){document.getElementById("low").textContent=binary.run?binary.low:"—";document.getElementById("high").textContent=binary.run?binary.high:"—";document.getElementById("mid").textContent=binary.run&&binary.low<=binary.high?Math.floor((binary.low+binary.high)/2):"—"}
function binaryStep(){if(!binary.run)return;if(binary.low>binary.high){binary.run=false;updateRange();document.getElementById("binaryStatus").textContent="Not Found";log("binaryLog",`Search range is empty. ${binary.target} was not found.`);return}let m=Math.floor((binary.low+binary.high)/2);binary.count++;document.getElementById("binaryCount").textContent=binary.count;renderArray(m);if(arr[m]===binary.target){binary.run=false;document.getElementById("binaryStatus").textContent="Found ✓";log("binaryLog",`MID = ${m}; 🐧${arr[m]} equals ${binary.target}. Target found!`);updateRange();return}if(arr[m]<binary.target){log("binaryLog",`MID = ${m}; ${arr[m]} is smaller than ${binary.target}. Move LOW to ${m+1}.`);binary.low=m+1}else{log("binaryLog",`MID = ${m}; ${arr[m]} is larger than ${binary.target}. Move HIGH to ${m-1}.`);binary.high=m-1}updateRange()}
function resetView(){linear.run=false;binary.run=false;renderArray();document.getElementById("linearStatus").textContent="Ready";document.getElementById("binaryStatus").textContent="Ready";updateRange()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab-content").forEach(x=>x.classList.add("hidden"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.remove("hidden")});
renderArray();updateRange();
